# Generated by Django 5.2.10 on 2026-02-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo', models.CharField(choices=[('DEP', 'Depósito'), ('RET', 'Retiro/Pago'), ('TRA', 'Transferencia'), ('REE', 'Reembolso')], max_length=3)),
                ('monto', models.IntegerField()),
                ('saldo_anterior', models.IntegerField()),
                ('saldo_posterior', models.IntegerField()),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='card.card')),
            ],
            options={
                'db_table': 'transaction_history',
                'ordering': ['-fecha_operacion'],
            },
        ),
    ]
