# Generated by Django 5.2.11 on 2026-02-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='monto',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='saldo_anterior',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='saldo_posterior',
            field=models.BigIntegerField(),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['card', '-fecha_operacion'], name='transaction_card_id_a718bd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tipo'], name='transaction_tipo_70bec5_idx'),
        ),
    ]
