# Generated by Django 5.2.11 on 2026-02-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='numero_tarjeta',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
